language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t missym2/mugwump-frontend -f Dockerfile.dev .

script:
    - docker run -e CI=true missym2/mugwump-frontend npm run test -- --coverage
